[phases.setup]
nixPkgs = ["python39"]
nixLibs = ["gcc", "libxml2", "libxslt"]

[phases.install]
cmds = ["cd backend && python3.9 -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python3.9 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"

